# Generated by Django 4.2.6 on 2024-02-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersroles',
            table='users_roles',
        ),
    ]
