# Generated by Django 4.2.6 on 2024-02-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0002_alter_usersroles_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
